project:
  type: website

website:
  title: "Data Management for Ag Scientists"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-workflow.qmd
        text: "Project Management"
  sidebar: 
    - href: project-workflow.qmd
      text: "Project Management"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



